#ifndef TPRK77_RGB_MODES_H
#define TPRK77_RGB_MODES_H

const int PROGMEM tprk77_rgb_modes[] = {
  RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE,
  RGB_MATRIX_SOLID_MULTISPLASH,
  RGB_MATRIX_BREATHING,
  RGB_MATRIX_SOLID_COLOR,
  RGB_MATRIX_MULTISPLASH,
  RGB_MATRIX_RAINBOW_MOVING_CHEVRON,
  RGB_MATRIX_CYCLE_SPIRAL,
  RGB_MATRIX_PINWHEELS
};

const int PROGMEM tprk77_num_rgb_modes = 8;

#endif
